### ISSUE TITLE
facebook, google, github같은 social 로그인할때 gradle dependency 설정

### ISSUE THREAD

**Issue by LeoHeo** [LeoHeo/collect#8]
## github, facebook만 social login을 하겠다.

```
compile group: 'org.springframework.security', name: 'spring-security-oauth2-client', version: "${oauth2ClientVersion}"
```

## google, github, facebook social login을 하겠다.

```
compile group: 'org.springframework.security', name: 'spring-security-oauth2-client', version: "${oauth2ClientVersion}"
compile group: 'org.springframework.security', name: 'spring-security-oauth2-jose', version: "${joseVersion}"
```

**Comment by LeoHeo** [comment]
~~페이스북은~~
~~이메일 권한을 설정하면~~
~~그니깐 이메일을 공개안하게 설정하면~~

~~이메일을 못 가져가는 유저가 있습니다.~~

유저 판단은 `id`로 한다고 하지만 이슈 사항이 있습니다.

## issue 1
- 이메일로 무언가를 통보해야할때 어떻게 할것인가?

## issue 2
- 100명의 페이스북 유저가 있는데 70명의 유저가 이메일이 있고 30명은 공개를 안했을때
- DB의 값을 어떻게 매핑할 것인가?

**Comment by LeoHeo** [comment]
facebook의 user-info-uri을 변경해주면 email을 얻어 올 수 있습니다.
해당 방법은 [Spring Security 5 Configuring Custom Provider Properties](https://docs.spring.io/spring-security/site/docs/5.0.3.RELEASE/reference/htmlsingle/#jc-oauth2login-custom-provider-properties)에 나옵니다.

해당 방법을 사용하면 `application.yml`에 아래와 같이 입력하면 됩니다.

```yml
   facebook:
      client-id: {clien-id}
      client-secret: {client-secret}
provider:
   facebook:
       user-info-uri: https://graph.facebook.com/v2.12/me?fields=email,name
```

 인제 생각해볼 문제는

## issue 1
- 핸드폰번호로 가입한 사람의 경우 email을 어떻게 입력받을것인가?
